# Generated by Django 6.1 on 2026-09-27 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('debt_id', models.AutoField(primary_key=True, serialize=False)),
                ('debt_name', models.CharField(max_length=100)),
                ('counterparty_name', models.CharField(max_length=100)),
                ('debt_type', models.CharField(choices=[('borrowed', 'ยืมเงิน'), ('lent', 'ให้ยืมเงิน')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('flexible', 'ทยอยชำระ'), ('monthly', 'รายเดือน')], max_length=20)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('due_date', models.DateField()),
                ('payment_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'ดำเนินการอยู่'), ('paid', 'ชำระแล้ว')], default='ongoing', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts_counterparty', to='users.user')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('note', models.TextField(blank=True)),
                ('payment_status', models.CharField(choices=[('pending', 'รอชำระ'), ('partial', 'ชำระบางส่วน'), ('paid', 'ชำระแล้ว'), ('overdue', 'เกินกำหนด')], default='pending', max_length=20)),
                ('confirm_status', models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('confirmed', 'ยืนยันแล้ว'), ('rejected', 'ไม่ผ่านการตรวจสอบ')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debts')),
            ],
        ),
    ]
