# Generated by Django 6.1 on 2026-10-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debts',
            old_name='counterparty_uid',
            new_name='counterparty',
        ),
        migrations.RenameField(
            model_name='debts',
            old_name='debt_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='debts',
            old_name='debt_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='debts',
            old_name='debt_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='debts',
            old_name='uid',
            new_name='user',
        ),
    ]
