# Generated by Django 6.1 on 2026-10-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_rename_counterparty_uid_debts_counterparty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
