# Generated by Django 6.1 on 2026-10-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_debts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='color',
            field=models.CharField(default='purple', max_length=30),
        ),
        migrations.AddField(
            model_name='debts',
            name='icon',
            field=models.CharField(default='school', max_length=30),
        ),
    ]
