# Generated by Django 6.1 on 2026-10-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_debts_color_debts_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='proof_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
