# Generated by Django 6.1 on 2026-10-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0005_alter_payments_proof_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debts',
            old_name='payment_day',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='payment_date',
            new_name='paid_date',
        ),
    ]
