# Generated by Django 6.1 on 2026-09-07 09:24

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_updated_at_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(default=users.models.generate_user_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
